version: "1.0"

detect_relations: true
directory: assets-alt

User:
  comment: "This asset contains information about registered users"
  columns:
    id: integer
    username: string
    password: string
    contact_id: integer

Contact:
  directory: assets-alt2
  comment: "This asset contains information about a user's contact info"
  columns:
    id: integer
    first_name: string
    last_name: string
    phone: string
    email: string
    address: string
    country_id: string

Countries:
  columns:
    code:
      type: string(2)
      primary: true
    name:
      type: string(255)
